name: LRU Cache Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up build environment
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Build the test executable
      - name: Build tests
        run: make all

      # Run the test executable
      - name: Run tests
        run: make test

      # Clean up after running tests
      - name: Clean up
        run: make clean
